name: Create Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:

    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Load cached dependencies
      uses: actions/cache@v3.3.1
      id: cache
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      id: install-dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Try to build the packages
      id: build-packages
      run: npm run build:packages

